modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="energia"
version="0.0.1"
displayName="energia"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="jokay03J"

[[dependencies.energia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




